language: scala
scala:
  - 2.11.8
jdk:
    - oraclejdk8
env:
  - PLAY_VERSION=2.4.4
#cache:
#  directories:
#    - '$HOME/.ivy2/cache'
#script: play-${PLAY_VERSION}/play test
#before_script:
#  - unset SBT_OPTS JVM_OPTS
#script: ./activator test