language: scala
scala:
  - 2.11.8
env:
  - PLAY_VERSION=2.4.4
#before_script:
#  - wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
#  - unzip -q play-${PLAY_VERSION}.zip
#script: play-${PLAY_VERSION}/play test
script: ./activator test