language: scala
scala:
  - 2.11.11
  #- 2.12.2

# safelist
branches:
  only:
  - master
  
sudo: false
dist: trusty
jdk:
    - oraclejdk8
    - openjdk8
env:
  - PLAY_VERSION=2.5.15
cache:
  directories:
    - '$HOME/.ivy2/cache'
    - '$HOME/.sbt/boot/'

after_success:
  - UPDATEIMPACT_API_KEY="zYy2GeIf9Gcm9JuT7dvcutEzZhkxJgNL" sbt updateImpactSubmit
