language: scala
scala:
  - 2.11.11
  - 2.12.2
sudo: false
dist: trusty
jdk:
    - oraclejdk8
    - openjdk8
env:
  - PLAY_VERSION=2.5.14
cache:
  directories:
    - '$HOME/.ivy2/cache'
    - '$HOME/.sbt/boot/'
