# base image
FROM node:10.15.3-jessie as builder

# set working directory
RUN mkdir /usr/src/client
WORKDIR /usr/src/client

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/client/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/client/package.json
RUN npm install --silent
RUN npm install react-scripts@1.1.1 -g --silent
COPY . /usr/src/client
RUN npm run build


# prod env
FROM nginx:stable
COPY --from=builder /usr/src/client/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

